services:
  postgres:
    image: postgres:16-alpine
    container_name: bac-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bac_bank
      POSTGRES_USER: bac_user
      POSTGRES_PASSWORD: bac_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4-standalone
    container_name: bac-adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    container_name: bac-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
